apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: istiod
  namespace: argocd
spec: 
  destination:
    namespace: istio-system
    server: "https://kubernetes.default.svc"
  project: default
  source:
    repoURL: 'https://istio-release.storage.googleapis.com/charts'
    targetRevision: 1.13.4
    chart: istiod
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
# ignore this originally to test the case - 88
# similar issue to what I've seen in ALB and linkerd charts
  # ignoreDifferences:
  #   - group: admissionregistration.k8s.io
  #     kind: MutatingWebhookConfiguration
  #     jqPathExpressions:
  #       - '.webhooks[]?.clientConfig.caBundle'


    
