apiVersion: v1
kind: Secret
metadata:
  name: private-repo-helm
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: helm
  name: argo
  url: https://my.helm.repo/name
  password: # password goes here, NOTE: dont push secrets into git, use sealed secrets as a solution for secrets in gitops.
  username: my-token
  # or
  tlsClientCertData:
  tlsClientCertKey:
# argocd cli and ui also can add this